trigger: none
pool: Default
stages:
  - stage: 
    jobs:
      - job: 
        steps:
        - task: NodeTaskRunnerInstaller@0
          inputs:
            nodeVersion: '16'
        - task: PowerShell@2
          inputs:
            targetType: 'inline'
            script: 'npm install'
        
        - task: PowerShell@2
          inputs:
            targetType: 'inline'
            script: 'npm run build'
        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: '$(Pipeline.Workspace)'
            artifact: 'npm_build'
            publishLocation: 'pipeline'
        