trigger: none
pool: Default
name: applicationPipeline
stages:
  - stage: CIPipeline
    displayName: "Continues Integration Pipeline"
    jobs:
      - job: 
        steps:
        - task: NodeTaskRunnerInstaller@0
          inputs:
            nodeVersion: '16'
        - task: PowerShell@2
          inputs:
            targetType: 'inline'
            script: 'npm install'

        - task: PowerShell@2
          inputs:
            targetType: 'inline'
            script: 'npm run build'
        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: '$(System.DefaultWorkingDirectory)/build/'
            artifact: 'todo-artifact'
            publishLocation: 'pipeline'
  - stage: ContinuesDeployment
    displayName: "Continues Deployment"
    jobs:
      - job: 
        steps:
        - task: SSH@0
          inputs:
            sshEndpoint: 'Deploymentssh'
            runOptions: 'inline'
            inline: |
              #!/bin/bash
              
              set -e
              
              echo "Checking Nginx..."
              
              if dpkg -s nginx >/dev/null 2>&1; then
                  echo "Nginx already installed"
              else
                  echo "Installing Nginx..."
                  sudo apt update -y
                  sudo apt install -y nginx
                  echo "Nginx installed"
              fi
              
              echo "Starting Nginx..."
              sudo systemctl start nginx
              
              # Suppress harmless stderr
              sudo systemctl enable nginx 2>/dev/null
              
              echo "Done 🚀"
            readyTimeout: '20000'
        - task: DownloadPipelineArtifact@2
          inputs:
            buildType: 'specific'
            project: '36a23b08-b637-49fe-9813-d340f2b532e5'
            definition: '3'
            buildVersionToDownload: 'specific'
            pipelineId: '70'
            artifactName: 'todo-artifact'
            targetPath: '$(System.DefaultWorkingDirectory)\downloaded-artifacts'

        - task: CopyFilesOverSSH@0
          inputs:
            sshEndpoint: 'Deploymentssh'
            sourceFolder: '$(System.DefaultWorkingDirectory)\downloaded-artifacts'
            contents: '**'
            targetFolder: '/home/azureadmin/'
            cleanTargetFolder: true
            readyTimeout: '20000'

        - task: SSH@0
          inputs:
            sshEndpoint: 'Deploymentssh'
            runOptions: 'commands'
            commands: 'sudo scp -r /home/azureadmin/* /var/www/html'
            readyTimeout: '20000'
        